# serverless.yml

service: thesis_serverless

provider:
  name: openwhisk
  runtime: nodejs:10
  memory: 1024
  timeout: 60

plugins:
  - serverless-openwhisk


functions:
  handle_cloudant_query:
    handler: apis/handle_cloudant_query/main.handler
    name: thesis_demo_2/handle_cloudant_query
  fetch_yappl_for_user:
    handler: cloudant/fetch_yappl_for_user/main.handler
    name: thesis_demo_2/fetch_yappl_for_user
  yappl_parser:
    handler: yappl_parser/main.handler
    name: thesis_demo_2/yappl_parser
  transformation_map_maker:
    handler: transformation_map_maker/main.handler
    name: thesis_demo_2/transformation_map_maker
  user_fetch_preparer:
    handler: user_fetch_preparer/main.handler
    name: thesis_demo_2/user_fetch_preparer
  fetch_user_data:
    handler: cloudant/fetch_user_data/main.handler
    name: thesis_demo_2/fetch_user_data
  transformation_orchestration_preparer:
    handler: transformation_orchestration/transformation_orchestration_preparer/main.handler
    name: thesis_demo_2/transformation_orchestration_preparer
  transformation_orchestration:
    handler: transformation_orchestration/transformation_orchestration/non_conductor.handler
    name: thesis_demo_2/transformation_orchestration
    conductor: true
  # helpers called elsewhere
  graph_checker:
    handler: graph_checker/main.handler
    name: thesis_demo_2/graph_checker
  anonymizer:
    handler: transformation_orchestration/anonymizer/main.handler
    name: thesis_demo_2/anonymizer
  none:
    handler: transformation_orchestration/none/main.handler
    name: thesis_demo_2/none
  only_provider:
    handler: transformation_orchestration/only_provider/main.handler
    name: thesis_demo_2/only_provider
  # sequences
  api_yappl_parse_maker_fetcher_transformator:
    name: thesis_demo_2/api_yappl_parse_maker_fetcher_transformator
    sequence:
      - handle_cloudant_query
      - fetch_yappl_for_user
      - yappl_parser
      - transformation_map_maker
      - user_fetch_preparer
      - fetch_user_data
      - transformation_orchestration_preparer
      - transformation_orchestration
