language: node_js
node_js:
  - 6
  - 8
  - 10

before_install:
  - cd ./functions/tests

install:
  - npm install -g jest
  - npm install

script:
  - npm run test

notifications:
  email:
    on_success: never
    on_failure: always
